### ISSUE TITLE
Usage of Sleep

### ISSUE THREAD

**Issue by johnjones4** [adafruit/Adafruit_CircuitPython_BMP3XX#11]
https://github.com/adafruit/Adafruit_CircuitPython_BMP3XX/blob/488b7af1fd3f272416d5634831da5acfabc2c5b4/adafruit_bmp3xx.py#L160

Is there a reason `time.sleep(0.002)` is used here rather than just pass? Or is 0.002 seconds specific to the device?

**Comment by caternuson** [comment]
Nothing specific to the device. Just providing a small wait time for the busy-wait loop.

Is the delay causing issues?

**Comment by johnjones4** [comment]
I'm using this to measure altitude from a model rocket, and so I'd like to sample as often as possible on ascent. I changed it to just use `pass` and it seems to boost performance without any negative impact.

**Comment by jposada202020** [comment]
@caternuson Do you think is a good Idea to create a parameter in the library to be set and modify this time?

**Comment by jposada202020** [comment]
Did some test with and without the sleep, the average difference with and without time between reading is 8ms. This was done taking three different readings intervals of [0.3, 0.5 1.0] seconds.

**Comment by caternuson** [comment]
@jposada202020 sorry, missed your previous mention. yah, that's probably fine. i think just `pass` in the loop would also work, but have had comments in PRs that say adding a call to `sleep()` is "better".

"reading as fast as possible" can be slowed down by other things though, like i2c bus speed.

**Comment by jposada202020** [comment]
will do @caternuson Thanks

**Comment by jposada202020** [comment]
We added the attribute in the library, following your input @caternuson we keep the time.sleep. this is a private attribute. This will help people in corner cases, and not breaking old code already written. Thanks, closing for now.
