### ISSUE TITLE
BMP390

### ISSUE THREAD

**Issue by sailoog** [adafruit/Adafruit_CircuitPython_BMP3XX#12]
_CHIP_ID should be 0x60 instead of 0x50 to make BMP390 work:
https://github.com/adafruit/Adafruit_CircuitPython_BMP3XX/blob/488b7af1fd3f272416d5634831da5acfabc2c5b4/adafruit_bmp3xx.py#L57

**Comment by ladyada** [comment]
try https://github.com/adafruit/Adafruit_CircuitPython_BMP3XX/pull/13

**Comment by sailoog** [comment]
Sorry for the delay, it works for us. Thanks!

**Comment by jposada202020** [comment]
Solution Merged in #13 . And working. Closing
