### ISSUE TITLE
BMP390 Now Reporting Negative Altitude?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [adafruit/Adafruit_CircuitPython_BMP3XX#21]
Been testing two BMP390 sensors.  Using Python 3.9.2, native to Pi OS 11.  After testing for a while, returned to testing, and now, both sensors are reporting negative altitude values.  Temperature and pressure are correct, not altitude.  Any idea why this is happening?

\# python3 --version
Python 3.9.2

`
import time
import board
import adafruit_bmp3xx

\# This Must Be Adjusted For Actual Location...
LEVEL=1013.25

\# Sampling...
TEMPERATURE=2
PRESSURE=8

\#

theBus=board.I2C()
theSensor=adafruit_bmp3xx.BMP3XX_I2C(theBus)

theSensor.pressure_oversampling=PRESSURE
theSensor.temperature_oversampling=TEMPERATURE
theSensor.sea_level_pressure=LEVEL

print("Temperature %0.1f C" % theSensor.temperature)
print("Pressure %0.1f hPa" % theSensor.pressure)
print("Altitude %0.1f m" % theSensor.altitude)
`

Example...
\# python3 BMP390.py
Temperature 26.6 C
Pressure 1017.3 hPa
Altitude -33.1 m

**Comment by ladyada** [comment]
see

https://learn.adafruit.com/adafruit-bmp388-bmp390-bmp3xx/python-circuitpython#circuitpython-and-python-usage-3022491-12


```
For altitude, you'll want to set the pressure at sea level for your location to get the most accurate measurement (remember these sensors can only infer altitude based on pressure and need a set calibration point).  Look at your local weather report for a pressure at sea level reading and set the sea_level_pressure property:


bmp.sea_level_pressure = 1013.25

Then read the altitude property for a more accurate altitude reading (but remember this altitude will fluctuate based on atmospheric pressure changes!):
```

**Comment by caternuson** [comment]
And just to point out it's working as expected, since you used the standard day value for sea level pressure:
```
# This Must Be Adjusted For Actual Location...
LEVEL=1013.25
```
but actual local pressure is greater:
```
Pressure 1017.3 hPa
```
that equates to an altitude *lower* than sea level, i.e. negative.

**Comment by caternuson** [comment]
Also good info here explaining how the sea level setting affects things and why it's important:
https://learn.adafruit.com/clue-altimeter

**Comment by Jibun-no-Kage** [comment]
No... I know about the setting to sea level pressure for my specific location.  That is not the issue.  The issue is, the code this morning was working fine... now it is not.  I have configured and engineered many of these sensors.  I need to know how or why the code, i.e. Adafruit source, can generate a negative number as noted.  Even if you use the 'generic' location, the result should not be negative!  The recognized average for sea level pressure is for testing is 1013.25.  So the argument that the minimum value of 1017.3 makes no sense either, when I use it, I get -11.4m.

As for using 1013.25, And I quote...
The average pressure at mean sea-level (MSL) in the International Standard Atmosphere (ISA) is 1013.25 hPa, or 1 atmosphere (atm), or 29.92 inches of mercury. Pressure (p), mass (m), and the acceleration due to gravity (g), are related by P = F/A = (m*g)/A, where A is surface area.
[https://en.wikipedia.org/wiki/Atmospheric_pressure
](url)

So clearly something odd it going on at the moment with the Adafruit BMP3XX code.  What are the conditions that can contribute to this?

**Comment by caternuson** [comment]
It's reporting the altitude expected for the current local pressure of 1017.3 hPa and the input sea level pressure of 1013.25 hPa.
```python
>>> (1 - (1017.3 / 1013.25)**0.190284) * 44307.69396
-33.64481648853728
```
